apiVersion: v2
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  selector:
    app: wil-playground-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP